In [4]:
%run regression.py

Current working directory: C:\Users\sashe\mlops\src\outputs\2024-02-25\15-00-29

Transformation Pipeline and Model Successfully Saved